version: '3.7'

services:

  property_me_be:
    build:
      context: .
      dockerfile: ./Local_Dockerfile
    command: npm run dev
    container_name: property_finder
    volumes:
      - ./:/home/node
      - /home/node/node_modules
    ports:
      - '7890:7890'
    depends_on:
      - property_db
    env_file:
      - .env
    environment:
      - TZ=Asia/Karachi  # Corrected timezone
      - DATABASE_URL=postgres://postgres:12345678@property_db_container:5432/property_me  # PostgreSQL connection URL
      - DB_HOST=property_db_container  # PostgreSQL container name
      - DB_PORT=5432  # PostgreSQL default port
      - DB_DRIVER=postgres
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CORS_ALLOWED_HOSTS=${CORS_ALLOWED_HOSTS}

  property_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: property_me
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      TZ: Asia/Karachi  # Corrected timezone
    container_name: property_db_container
    ports:
      - '3390:5432'  # Exposing PostgreSQL's default port
